// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksWifi.InfrastructureServices.Gateways.Database;

namespace ParksWifi.WebService.Migrations
{
    [DbContext(typeof(WifiHotspotContext))]
    [Migration("20210510171937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ParksWifi.DomainObjects.WifiHotspot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FunctionFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WiFiName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WifiHotspots");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Moscow_WiFi_Free",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Парк культуры и отдыха «Сокольники»"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Moscow_WiFi_Free",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Музейно-парковый комплекс «Северное Тушино», парк «Северное Тушино»  "
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Moscow_WiFi_Free",
                            ParkName = "Государственное бюджетное учреждение культуры города Москвы «Государственный Дарвиновский музей», территория около музея"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Moscow_WiFi_Free",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Парк культуры и отдыха «Фили», Парк 50-летия Октября"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
